### ISSUE TITLE
TODO for local MVP

### ISSUE THREAD

**Issue by domino14** [domino14/smart-board#1]
- [ ] keep track of board state, including score, as game progresses
- [ ] split up image when it's bot's turn into board + rack; send both to scrabblecam api. only show the board part of the image in the interface
- [ ] have some way of resolving a blank to a fixed letter for the life of a game
- [ ] show scores in interface
- [ ] build up CGP and send to BestBot lambda function or similar
- [ ] select lexicon somehow 
- [ ] have a way to communicate bot's move back to the player (audio?). In interface ok for now.
- [ ] bot should validate played moves and board state; warn if different.
